[package]
name = "rustsnake"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.27.2"
egui = "0.27.2"
egui_extras = { version = "0.27.2", features = ["image"] }
env_logger = "0.10.0"
rand = "0.9.2"

[[bin]]
name = "rustsnake"
path = "src/game.rs"
